---
title: "1-cleaning"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```
We'll need to use the following `R` packages:
```{r, message = FALSE}
library(tidyverse)  # tidyverse
library(ggrepel)    # for scatter plot point labels
library(kableExtra) # for printing tables
library(cowplot)    # for side by side plots
```


## Data Wrangling
```{r}
read.csv("pregnancy_diet.csv")
```




```{r}
pdiet = read.csv("pregnancy_diet.csv")

```

```{r}
pdiet1 = pdiet %>% mutate(mothers_race = str_sub(race..Mother.s.race, 4, -1)) %>%
  mutate(mother_race_ethnicity=str_sub(race_eth..Mother.s.race.ethnicity, 4, -1)) %>%
  mutate(mother_education=str_sub(education..Mother.s.education, 4, -1)) %>%
  mutate(orange_grapefruit_juice_freq=str_sub(DHP2..Orange.grapefruit.juice.frequency, 3, -1)) %>%
  mutate(other_fruit_juice_freq=str_sub(DHP3..Other.100..fruit.juice.juice.mixtures.frequency, 3, -1)) %>%
  mutate(other_fruit_drink_freq=str_sub(DHP4..Other.fruit.drinks.frequency, 3, -1)) %>%
  mutate(
    energy_drink_freq=str_sub(DHP6..Meal.replacement.energy.high.protein.beverages.frequency, 3, -1)) %>%
  mutate(soft_drinks_freq=str_sub(DHP7..Soft.drinks.soda.pop.frequency, 3, -1)) %>%
  mutate(applesauce_freq=str_sub(DHP13..Applesauce.frequency, 3, -1)) %>%
  mutate(apple_freq=str_sub(DHP14..Apples.frequency, 3, -1)) %>%
  mutate(pear_freq=str_sub(DHP15..Pears.frequency, 3, -1)) %>%
  mutate(banana_freq=str_sub(DHP16..Bananas.frequency, 3, -1)) %>%
  mutate(dried_fruit_freq=str_sub(DHP17..Dried.fruit.frequency, 3, -1)) %>%
  mutate(peach_freq=str_sub(DHP18..Peaches.nectarines.plums.frequency, 3, -1)) %>%
  mutate(grape_freq=str_sub(DHP19..Grapes.frequency, 3, -1)) %>%
  mutate(cantaloupe_freq=str_sub(DHP20..Cantaloupe.frequency, 3, -1)) %>%
  mutate(melon_freq=str_sub(DHP21..melon.other.than.cantaloupe.frequency, 3, -1)) %>%
  mutate(strawberry_freq=str_sub(DHP22..Strawberries.frequency, 3, -1)) %>%
  mutate(orange_freq=str_sub(DHP23..Oranges.tangerines.tangelos.frequency, 3, -1)) %>%
  mutate(grapefruit_freq=str_sub(DHP24..Grapefruit.frequency, 3, -1)) %>%
  mutate(other_fruit_freq=str_sub(DHP25..Other.kinds.of.fruit.frequency, 3, -1)) %>%
  mutate(roast_beef_sandwich_freq=str_sub(DHP66..Roast.beef.steak.in.sandwiches.frequency, 3, -1)) %>%
  mutate(chicken_turkey_freq=str_sub(DHP67..Turkey.chicken.cold.cuts.frequency, 3, -1)) %>%
  mutate(deli_ham_freq=str_sub(DHP68..Luncheon.deli.style.ham.frequency, 3, -1)) %>%
  mutate(other_coldcut_freq=str_sub(DHP69..Other.cold.cuts.or.luncheon.meats.frequency, 3, -1)) %>%
  mutate(hamburger_freq=str_sub(DHP72..Beef.hamburgers.cheeseburgers.frequency, 3, -1)) %>%
  select(-N_recvd..Date.neonatal.questionnaire.received, -race..Mother.s.race,
         -race_eth..Mother.s.race.ethnicity, -education..Mother.s.education,
         -DHPdate_flag..Prenatal.DHQ.was.completed.before.or.after.delivery,
         -P6_1..Mother.enrolled.in.WIC.in.past.month, -P14j..Changed.diet..Vitamin.mineral,
         -DHP2..Orange.grapefruit.juice.frequency, -DHP3..Other.100..fruit.juice.juice.mixtures.frequency,
         -DHP4..Other.fruit.drinks.frequency,
         -DHP6..Meal.replacement.energy.high.protein.beverages.frequency,
         -DHP7..Soft.drinks.soda.pop.frequency, -DHP13..Applesauce.frequency, -DHP14..Apples.frequency,
         -DHP15..Pears.frequency, -DHP16..Bananas.frequency, -DHP17..Dried.fruit.frequency,
         -DHP18..Peaches.nectarines.plums.frequency, -DHP19..Grapes.frequency, -DHP20..Cantaloupe.frequency,
         -DHP21..melon.other.than.cantaloupe.frequency, -DHP22..Strawberries.frequency,
         -DHP23..Oranges.tangerines.tangelos.frequency, -DHP24..Grapefruit.frequency,
         -DHP25..Other.kinds.of.fruit.frequency, -DHP66..Roast.beef.steak.in.sandwiches.frequency,
         -DHP67..Turkey.chicken.cold.cuts.frequency, -DHP68..Luncheon.deli.style.ham.frequency,
         -DHP69..Other.cold.cuts.or.luncheon.meats.frequency,
         -DHP72..Beef.hamburgers.cheeseburgers.frequency)
```

```{r}
pdiet2 = pdiet1 %>% mutate(ground_beef_mix_freq=str_sub(DHP73..Ground.beef.in.mixtures.frequency, 3, -1)) %>%
  mutate(ground_beef_mix_freq=str_sub(DHP73..Ground.beef.in.mixtures.frequency, 3, -1)) %>%
  mutate(hotdog_freq=str_sub(DHP74..Hot.dogs.frankfurters.frequency, 3, -1)) %>%
  mutate(beef_mix_freq=str_sub(DHP75..Beef.mixtures.frequency, 3, -1),
         roast_beef_mix_freq=str_sub(DHP76..Roast.beef.pot.roast.frequency, 3, -1),
         steak_freq=str_sub(DHP77..Steak..beef..frequency, 3, -1),
         ribs_freq=str_sub(DHP78..Pork.beef.spareribs.frequency, 3, -1),
         chicken_freq=str_sub(DHP81..Baked.broiled.roasted.stewed.fried.chicken.frequency,3, -1),
         ham_freq=str_sub(DHP82..Baked.ham.ham.steak.frequency, 3, -1),
         pork_freq=str_sub(DHP83..Pork.frequency, 3, -1), 
         liver_freq=str_sub(DHP85..Liver.liverwurst.frequency, 3, -1),
         bacon_freq=str_sub(DHP86..Bacon.frequency, 3,-1),
         sausage_freq=str_sub(DHP87..Sausage.frequency, 3, -1),
         fruit_cobbler_freq=str_sub(DHP112..Fruit.crisp.cobbler.strudel.frequency,3, -1),
         pie_freq=str_sub(DHP113..Pie.frequency, 3, -1), vegetarian_diet=str_sub(
           DHP136..Vegetarian.diet, 3, -1), multivitamins=str_sub(DHP138..Took.multivitamins, 3, -1),
         prenatal_vitamin_freq=str_sub(DHP139..Prenatal.vitamins.frequency, 3, -1),
         fruit_cobbler_amount=str_sub(DHP112a..Fruit.crisp.cobbler.strudel.amount, 3, -1),
         pie_amount=str_sub(DHP113a..Pie.amount, 3, -1), fruit_pie_freq=str_sub(
           DHP113b..Fruit.pie.frequency, 3, -1),
         pumpkin_sweet_pie_freq=str_sub(DHP113d..Pumpkin.sweet.potato.pie.frequency, 3, -1),
         meat_excluded=str_sub(DHP136a1..Meat.excluded, 1, 1),
         poultry_excluded=str_sub(DHP136a2..Poultry.excluded, 1, 1),
         seafood_excluded=str_sub(DHP136a3..Fish.and.seafood.excluded, 1, 1),
         eggs_excluded=str_sub(DHP136a4..Eggs.excludee, 1, 1),
         dairy_excluded=str_sub(DHP136a5..Diary.products.excluded, 1, 1),
         applesauce_amount=str_sub(DHP13a..Applesauce.amount, 3, -1),
         multivitamin_yrs=str_sub(DHP140b..Number.of.years.taking.multivitamins, 3, -1),
         calcium_amount=str_sub(DHP145a..Calcium.amount.day, 3, -1),
         iron_supplements=str_sub(DHP147j..Taking.Iron.single.supplements.once.per.week.or.more, 1, 1),
         apple_amount=str_sub(DHP14a..Apples.amount, 3, -1), pear_amount=str_sub(
           DHP15a..Pears.amount, 3, -1), banana_amount=str_sub(DHP16a..Bananas.amount, 3, -1),
         dried_fruit_amount=str_sub(DHP17a..Dried.fruit.amount, 3, -1),
         peach_amount=str_sub(DHP18a..Peaches.nectarines.plums.amount, 3, -1),
         grape_amount=str_sub(DHP19a..Grapes.amount, 3, -1),
         cantaloupe_amount=str_sub(DHP20a..Cantaloupe.amount, 3, -1),
         melon_amount=str_sub(DHP21a..melon.other.than.cantaloupe.amount, 3, -1),
         strawberry_amount=str_sub(DHP22a..Strawberries.amount, 3, -1),
         orange_amount=str_sub(DHP23a..Oranges.tangerines.tangelos.amount, 3, -1),
         grapefruit_amount=str_sub(DHP24a..Grapefruit.amount, 3, -1),
         other_fruit_amount=str_sub(DHP113a..Pie.amount, 3, -1),
         orange_grapefruit_juice_amount=str_sub(DHP2a..Orange.grapefruit.juice.amount, 3, -1),
         calcium_og_juice_freq=str_sub(DHP2b..Calcium.fortified.orange.grapefruit.juice.frequency, 3, -1),
         vitamin_d_org_juice_freq=str_sub(
           DHP2c..Vitamin.D.fortified.orange.grapefruit.juice.frequency, 3, -1),
         other_fruit_juice_amount=str_sub(DHP3a..Other.100..fruit.juice.juice.mixtures.amount, 3, -1),
         calcium_other_fruit_juice_freq=str_sub(
           DHP3b..calcium.fortified.other.fruit.juice.fruit.juice.mixtures.frequency, 3, -1),
         vitamin_d_other_fruit_juice_freq=str_sub(
           DHP3c..Vitamin.D.fortified.other.fruit.juice.fruit.juice.mixtures.frequency, 3, -1),
         other_fruit_drink_amount=str_sub(DHP4a..Other.fruit.drinks.amount, 3, -1),
         diet_fruit_drink_freq=str_sub(DHP4b..Diet.sugar.free.fruit.drinks.frequency, 3, -1)) %>%
  select(-DHP73..Ground.beef.in.mixtures.frequency, -DHP74..Hot.dogs.frankfurters.frequency,
         -DHP75..Beef.mixtures.frequency, -DHP76..Roast.beef.pot.roast.frequency,
         -DHP77..Steak..beef..frequency, -DHP78..Pork.beef.spareribs.frequency,
         -DHP81..Baked.broiled.roasted.stewed.fried.chicken.frequency,
         -DHP82..Baked.ham.ham.steak.frequency, -DHP83..Pork.frequency,
         -DHP85..Liver.liverwurst.frequency, -DHP86..Bacon.frequency, -DHP87..Sausage.frequency,
         -DHP112..Fruit.crisp.cobbler.strudel.frequency, -DHP113..Pie.frequency, -DHP136..Vegetarian.diet,
         -DHP138..Took.multivitamins, -DHP139..Prenatal.vitamins.frequency,
         -DHP112a..Fruit.crisp.cobbler.strudel.amount, -DHP113a..Pie.amount, -DHP113b..Fruit.pie.frequency,
         -DHP113d..Pumpkin.sweet.potato.pie.frequency, -DHP136a1..Meat.excluded, -DHP136a2..Poultry.excluded,
         -DHP136a3..Fish.and.seafood.excluded, -DHP136a4..Eggs.excludee, -DHP136a5..Diary.products.excluded,
         -DHP13a..Applesauce.amount, -DHP140b..Number.of.years.taking.multivitamins,
         -DHP145a..Calcium.amount.day, -DHP147j..Taking.Iron.single.supplements.once.per.week.or.more,
         -DHP14a..Apples.amount, -DHP15a..Pears.amount, -DHP16a..Bananas.amount, -DHP17a..Dried.fruit.amount,
         -DHP18a..Peaches.nectarines.plums.amount, -DHP19a..Grapes.amount, -DHP20a..Cantaloupe.amount,
         -DHP21a..melon.other.than.cantaloupe.amount, -DHP22a..Strawberries.amount)

```

```{r}
pdiet3 = pdiet2 %>% select(-DHP23a..Oranges.tangerines.tangelos.amount, -DHP24a..Grapefruit.amount,
                           -DHP25a..Other.kinds.of.fruit.amount, -DHP2a..Orange.grapefruit.juice.amount,
                           -DHP2b..Calcium.fortified.orange.grapefruit.juice.frequency,
                           -DHP2c..Vitamin.D.fortified.orange.grapefruit.juice.frequency,
                           -DHP3a..Other.100..fruit.juice.juice.mixtures.amount,
                           -DHP3b..calcium.fortified.other.fruit.juice.fruit.juice.mixtures.frequency,
                           -DHP3c..Vitamin.D.fortified.other.fruit.juice.fruit.juice.mixtures.frequency,
                           -DHP4a..Other.fruit.drinks.amount,
                           -DHP4b..Diet.sugar.free.fruit.drinks.frequency) %>%
  mutate(roast_beef_sandwich_amount=str_sub(DHP66a..Roast.beef.steak.in.sandwiches.amount, 3, -1),
         chicken_turkey_amount=str_sub(DHP67a..Turkey.chicken.cold.cuts.amount, 3, -1),
         ham_amount=str_sub(DHP68a..Luncheon.deli.style.ham.amount, 3, -1),
         lowfat_ham_freq=str_sub(DHP68b..Light.low.fat.fat.free.luncheon.deli.style.ham.frequency, 3, -1),
         other_coldcut_amount=str_sub(DHP69a..Other.cold.cuts.or.luncheon.meats.amount, 3, -1),
         lowfat_meat_freq=str_sub(DHP69b..Light.low.fat.fat.free.cold.cuts.luncheon.meats.frequency, 3, -1),
         enery_drink_amount=str_sub(DHP6a..Meal.replacement.energy.high.protein.beverages.amount, 3, -1)) %>%
  select(-DHP66a..Roast.beef.steak.in.sandwiches.amount, -DHP67a..Turkey.chicken.cold.cuts.amount,
         -DHP68a..Luncheon.deli.style.ham.amount,
         -DHP68b..Light.low.fat.fat.free.luncheon.deli.style.ham.frequency,
         -DHP69a..Other.cold.cuts.or.luncheon.meats.amount,
         -DHP69b..Light.low.fat.fat.free.cold.cuts.luncheon.meats.frequency,
         -DHP6a..Meal.replacement.energy.high.protein.beverages.amount)

```


```{r}

pdiet4 = pdiet3 %>% mutate(hamburger_amount=str_sub(DHP72a..Beef.hamburgers.cheeseburgers.amount, 3, -1),
         hamburger_lean_beef_freq=str_sub(
           DHP72b..Beef.hamburgers.cheeseburgers.made.with.lean.ground.beef.frequency, 3, -1),
         lowfat_hot_dog_freq = str_sub(DHP74b..Light.low.fat.hot.dogs.frequency, 3, -1),
         beef_mixture_amount = str_sub(DHP75a..Beef.mixtures.amount, 3, -1), 
         roast_beef_amount = str_sub(DHP76a..Roast.beef.pot.roast.amount, 3, -1),
         steak_amount = str_sub(DHP77a..Steak..beef..amount, 3, -1), 
         lean_steak_freq = str_sub(DHP77b..Lean.steak.frequency, 3, -1),
         ribs_amount = str_sub(DHP78a..Pork.beef.spareribs.amount, 3, -1),
         soda_amount = str_sub(DHP7a..Soft.drinks.soda.pop.frequency.amount, 3, -1), 
         diet_soda_freq = str_sub(DHP7b..Soft.drinks.soda.pop.diet.or.sugar.free.frequency, 3, -1),
         fried_chicken_freq = str_sub(DHP81b..Fried.chicken.chicken.nuggets.frequency, 3, -1),
         baked_ham_amount = str_sub(DHP82a..Baked.ham.ham.steak.amount, 3, -1),
         pork_amount = str_sub(DHP83a..Pork.amount, 3, -1), 
         liver_amount = str_sub(DHP85a..Liver.liverwurst.amount, 3, -1), 
         bacon_amount = str_sub(DHP86a..Bacon.amount, 3, -1), 
         lowfat_bacon_freq = str_sub(DHP86b..Light.low.fat.lean.bacon.frequency, 3, -1),
         sausage_amount = str_sub(DHP87a..Sausage.amount, 3, -1), 
         lowfat_sausage_freq = str_sub(DHP87b..Light.low.fat.lean.sausage.frequency, 3, -1), 
         lean_steak_freq = str_sub(DHP77b..Lean.steak.frequency, 3, -1), 
         hotdog_amount = str_sub(DHP74a..Hot.dogs.frankfurters.amount, 3, -1),
         region = str_sub(Region..Geographic.region, 4, -1),
         state = str_sub(State..State.of.residence, 5, -1), 
         household_size = str_sub(Hh_Size..Household.size, 1, 1), 
         dwelling_type = str_sub(Dwelling..Type.of.dwelling, 5, -1),
         marital_status = str_sub(Marital..Marital.status, 4, -1), 
         home_ownership = str_sub(Ownershp..Home.ownership, 4, -1),
         hispanic = str_sub(Hispanic..Hispanic.origin, 4, -1),
         male_employment_status = str_sub(M_Employ..Employment.status.of.male.partner, 4, -1),
         male_occupation = str_sub(M_Occup..Occupation.of.male.partner, 4, -1),
         occupation = str_sub(Occup..Occupation, 4, -1), 
         population_density = str_sub(Density..Population.density, 4, -1), 
         employment_status = str_sub(Employ..Employment.status, 4, -1), 
         gestational_diabetes = str_sub(P12..Gestational.diabetes.with.pregnancy, 4, -1), 
         mother_overweight = str_sub(P13g1..Mother.has.overweight.or.obesity, 1, 1), 
         father_overweight = str_sub(P13g2..Father.has.overweight.or.obesity, 1, 1), 
         work_during_baby_yr1 = str_sub(P23..Plan.to.work.for.pay.during.baby.s.first.year, 4, -1)) %>%
  select(-DHP73a..Beef.hamburgers.cheeseburgers.amount, -DHP72a..Beef.hamburgers.cheeseburgers.amount,
         -DHP72b..Beef.hamburgers.cheeseburgers.made.with.lean.ground.beef.frequency,
         -DHP74b..Light.low.fat.hot.dogs.frequency, -DHP75a..Beef.mixtures.amount,
         -DHP76a..Roast.beef.pot.roast.amount, -DHP77a..Steak..beef..amount,
         -DHP78a..Pork.beef.spareribs.amount, -DHP7a..Soft.drinks.soda.pop.frequency.amount,
         -DHP7b..Soft.drinks.soda.pop.diet.or.sugar.free.frequency,
         -DHP81b..Fried.chicken.chicken.nuggets.frequency, -DHP82a..Baked.ham.ham.steak.amount,
         -DHP83a..Pork.amount, -DHP85a..Liver.liverwurst.amount, -DHP86a..Bacon.amount,
         -DHP86b..Light.low.fat.lean.bacon.frequency, -DHP87a..Sausage.amount,
         -DHP87b..Light.low.fat.lean.sausage.frequency, -DHP74a..Hot.dogs.frankfurters.amount,
         -DHP77b..Lean.steak.frequency, -Region..Geographic.region, -State..State.of.residence,
         -Hh_Size..Household.size, -Dwelling..Type.of.dwelling, -Marital..Marital.status,
         -Ownershp..Home.ownership, -Hispanic..Hispanic.origin, -M_Employ..Employment.status.of.male.partner,
         -M_Occup..Occupation.of.male.partner, -Occup..Occupation, -Density..Population.density,
         -Employ..Employment.status, -P12..Gestational.diabetes.with.pregnancy,
         -P13g1..Mother.has.overweight.or.obesity, -P13g2..Father.has.overweight.or.obesity,
         -P23..Plan.to.work.for.pay.during.baby.s.first.year)
                           
                           
                           
    
```

```{r}

pdiet5 = pdiet4 %>% rename(pregnancy_weight_gain = N9..Weight.gain.during.pregnancy.in.pounds) %>%
  filter(!pregnancy_weight_gain == ".Q: No Q’naire data") %>% filter(
    !pregnancy_weight_gain == ".N: No Answer") %>% relocate(pregnancy_weight_gain) %>% 
  rename(mother_age = cleaned_age..Adjusted.Age, 
         poverty_income_ratio = PIRLEVEL..Income....of.poverty., 
         prepregnancy_bmi = BMI..Pre.pregnancy.BMI, 
         alcohol_g = DHPalcoholg..Alcohol...g, 
         number_of_dry_bean_pea_servings = DHPbeanpea..Number.of.dry.bean.and.pea.servings, 
         lean_meat_oz = DHPbfpklb..Oz.lean.meat.from.beef.pork.lamb.etc, 
         weeks_before_delivery_DHP_complete = DHPWksbirth..Weeks.until.the.birth.when.DHP.was.completed,
         avg_cigarettes_daily = P10..Current.average.daily.cigarettes.smoked, 
         other_babies = P41_1..Other.babies.respondent.had)


```









```{r}
#pdiet4 %>% mutate(employment_status = as.factor(employment_status), mothers_race = as.factor(mothers_race))


```





























