---
title: "2-exploration"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
# load packages
library(tidyverse)  # tidyverse
library(ggrepel)    # for scatter plot point labels
library(kableExtra) # for printing tables
library(cowplot)    # for side by side plots
library(corrplot) # correlation plots
# raincloud plots
if (!require(remotes)) {
  install.packages("remotes")
}
remotes::install_github('jorvlan/raincloudplots')

library(raincloudplots)
library(dplyr)
library(readr)
library(stringr)
source("functions/R_rainclouds.R")
```

```{r}
# load cleaned data
pdiet_data = read.csv("./../data/clean/pregnancy_data.csv")
pdiet_data_raw = read.csv("./../data/raw/pregnancy_diet.csv")
```

```{r}
# calculate median weight gain
median_weight_gain = pdiet_data %>%
  summarise(median(pregnancy_weight_gain)) %>%
  pull()

# create histogram of weight gain during pregnancy
hist = pdiet_data %>%
  ggplot(aes(x = pregnancy_weight_gain)) + 
  geom_histogram() +
  geom_vline(xintercept = median_weight_gain,
             linetype = "dashed") +
  labs(x = "Weight gain during pregnancy", 
       y = "Number of women") +
  theme_classic()

# save
ggsave(filename = "~/pregnancy-weight-gain-final-project/results/weight-gain-hist.png", 
       plot = hist, 
       device = "png", 
       width = 7, 
       height = 4)

```

```{r}
# raincloud of weight gain vs race
raincloudRacePlot <- ggplot(pdiet_data, aes(x = mother_race_ethnicity, y = pregnancy_weight_gain, fill = mother_race_ethnicity)) +
  geom_flat_violin(aes(fill = mother_race_ethnicity),position = position_nudge(x = .2, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA)+
  geom_point(aes(x = mother_race_ethnicity, y = pregnancy_weight_gain, color = mother_race_ethnicity),position = position_jitter(width = .15, height = 0), size = 1, shape = 20)+
  geom_boxplot(aes(x = mother_race_ethnicity, y = pregnancy_weight_gain, fill = mother_race_ethnicity),outlier.shape = NA, alpha = .5, width = .1, colour = "black")+
  scale_colour_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")+ theme_classic() + labs(x = "race/ethnicity", y = "weight gain during pregnancy") + 
  guides(x = guide_axis(n.dodge = 2))
raincloudRacePlot = raincloudRacePlot + labs(fill="race/ethnicity")

# save
ggsave(filename = "~/pregnancy-weight-gain-final-project/results/raincloud-race.png", 
       plot = raincloudRacePlot, 
       device = "png", 
       width = 7, 
       height = 4)
```

```{r}
# scatter plots of weight gain vs age, bmi, poverty/income ratio
age_scatter = pdiet_data %>% ggplot(aes(x=mother_age, y=pregnancy_weight_gain)) + geom_point() +
  labs(x="age", y="weight gain during pregnancy") + theme_bw()

bmi_scatter = pdiet_data %>% ggplot(aes(x=prepregnancy_bmi, y=pregnancy_weight_gain)) + geom_point() +
  labs(x="BMI before pregnancy", y="weight gain during pregnancy") + theme_bw()

povincome_scatter = pdiet_data %>% ggplot(aes(x=poverty_income_ratio, y=pregnancy_weight_gain)) + geom_point() +
  labs(x="poverty-income ratio", y="weight gain during pregnancy") + theme_bw()

# save
ggsave(filename = "~/pregnancy-weight-gain-final-project/results/age-scatter.png", 
       plot = age_scatter, 
       device = "png", 
       width = 7, 
       height = 4)

ggsave(filename = "~/pregnancy-weight-gain-final-project/results/bmi-scatter.png", 
       plot = bmi_scatter, 
       device = "png", 
       width = 7, 
       height = 4)

ggsave(filename = "~/pregnancy-weight-gain-final-project/results/povincome-scatter.png", 
       plot = povincome_scatter, 
       device = "png", 
       width = 7, 
       height = 4)
```

```{r, warning=FALSE}
# raincloud plot of weight gain vs education
raincloudEduPlot <- ggplot(pdiet_data, aes(x = mother_education, y = pregnancy_weight_gain, fill = mother_education)) +
  geom_flat_violin(aes(fill = mother_education),position = position_nudge(x = .2, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA)+
  geom_point(aes(x = mother_education, y = pregnancy_weight_gain, color = mother_education),position = position_jitter(width = .15, height = 0), size = 1, shape = 20)+
  geom_boxplot(aes(x = mother_education, y = pregnancy_weight_gain, fill = mother_education),outlier.shape = NA, alpha = .5, width = .1, colour = "black")+
  scale_colour_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")+ theme_classic() + labs(x = "education level", y = "weight gain during pregnancy") +
  guides(x = guide_axis(angle = 90))

# save
ggsave(filename = "~/pregnancy-weight-gain-final-project/results/raincloud-education.png", 
       plot = raincloudEduPlot, 
       device = "png", 
       width = 7, 
       height = 4)

```

```{r}
# correlation matrices for DHP variables
# subset only DHP variables
pdiet_DHP = pdiet_data[,substr(colnames(pdiet_data), 1, 3)=="DHP"]

# calculate correlation and make plot
corr = cor(pdiet_DHP)

png(height=1800, width=1800, file="~/pregnancy-weight-gain-final-project/results/DHP-correlation.png", type = "cairo")
corrplot(corr, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45, tl.cex = 0.7)
dev.off()

flattenCorrMatrix <- function(cormat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut]
    )
}
flattenCorrMatrix(corr)
flattenCorrMatrix(corr) %>% slice_max(cor, n=10)
```